### ISSUE TITLE
Technical requirement: grant instructor users with privilege to add categories

### ISSUE THREAD

**Issue by Sho-Shoo** [CMU-313/spring23-nodebb-team-c2#11]
One of the technical requirement of user story #8. Need to grant instructors with authorities to create new blog categories. 

Estimated effort: should be relatively easy to alter the setting. To be completed at the beginning of sprint 1 

Acceptance criteria: can test this by adding new tests testing of instructors can add new categories to the database. Considering replicating tests of admin adding new categories.

**Comment by destroyer806** [comment]
Try to grant permissions to instructors such that they have the ability to add post categories
