### ISSUE TITLE
Technical requirement: return proper view for instructors to add new blog category

### ISSUE THREAD

**Issue by Sho-Shoo** [CMU-313/spring23-nodebb-team-c2#12]
One of the technical requirements for user story #8. This will build upon technical requirement issue #10 and return the right view/interface to instructor users. 

Estimated effort: might need to obtain some front-end knowledge first and spend some time getting familiar with NodeBB's partials and widgets. Estimated to be completed between the start of the first sprint and the start of the second. 

Acceptance Criteria: by going to the url specified in #10, we can see the proper user interface of adding new category.

**Comment by destroyer806** [comment]
Try to fix admin checks such that instructors can access admin pages to add categories (because admins can add post categories currently)

**Comment by Sho-Shoo** [comment]
This is resolved by PR #19
