### ISSUE TITLE
Technical Requirement: Creating button in taskbar so an instructor can be routed to admin page

### ISSUE THREAD

**Issue by destroyer806** [CMU-313/spring23-nodebb-team-c2#15]
This is one of the technical requirement for user story https://github.com/CMU-313/spring23-nodebb-team-c2/issues/8. Need to add a front-end element in the task bar so that instructors can be routed to the admin page to add post categories

Estimated efforts: Since tpl files are new to the group, this task will require significant research and understanding of the code. 

Acceptance criteria: Button can route instructors/users to the admin page

**Comment by Sho-Shoo** [comment]
This is resolved by PR #19
