### ISSUE TITLE
Technical Requirement: Adding attribute to user such that there is differentiation between instructor and students.

### ISSUE THREAD

**Issue by destroyer806** [CMU-313/spring23-nodebb-team-c2#16]
This is one of the technical requirement for user story https://github.com/CMU-313/spring23-nodebb-team-c2/issues/8. We need to add an attribute in the user class so that students and instructors can be differentiated.

Estimated efforts: Given that the nodeBB user model is very convoluted, it may be difficult to manage and update a user attribute throughout the program. This technical requirement will be time consuming.

Acceptance criteria: Console print that will distinguish instructor vs student account

**Comment by Sho-Shoo** [comment]
This is resolved by PR #17
