### ISSUE TITLE
Write user guide documentation 

### ISSUE THREAD

**Issue by Sho-Shoo** [CMU-313/spring23-nodebb-team-c2#32]
- Create a new file UserGuide.md in the root directory of your repository
- In this file, provide a detailed outline of how to use and user test your new feature(s)
- Should also provide a link/description of where your added automated tests can be found, along with a description of what is being tested and why you believe the tests are sufficient for covering the changes that you have made

**Comment by destroyer806** [comment]
The UserGuide.md file has been created and uploaded to this repo, thus closing issue #32.
