### ISSUE TITLE
Allow instructors to create new blog categories

### ISSUE THREAD

**Issue by doreenvalmyr** [CMU-313/spring23-nodebb-team-c2#8]
Original user story: "As an instructor, I want to be able to open new blog categories in the course, so that I can better organize the discussions on the forum."

This user story is 3rd. It's important to allow instructors to create new categories that are specified to different groups. For example, an instructor could create class categories in order to have a specified location where students can discuss and ask questions regarding their classes.

**Comment by Sho-Shoo** [comment]
This is resolved by PR #17
